### ISSUE TITLE
Error while running SVE with Docker

### ISSUE THREAD

**Issue by tushardave26** [timothyjamesbecker/SVE#8]
Hello Timothy,

Thanks for the `SVE`. Great work.

I started playing with it recently. Unfortunately, the first time trying it did not work. I tried to replicate `step - 2` from the `repo` `README`. I already have some `BAM` which I want to use as a test case for `SVE`. 

Command line, I used:
```bash
$ sudo docker run --rm --user root -v ${PWD}:/data timothyjamesbecker/sve /bin/bash -c "/software/SVE/scripts/variant_processor.py -r /data/GRCh38.primary_assembly.genome.fa.fai -b /data/117_2991_a_exome.bam -o /data/vcfs/ -s breakdancer,gatk_haplo,delly,lumpy,cnvnator,pindel"
```

Error:
```bash
Unable to find image 'timothyjamesbecker/sve:latest' locally
latest: Pulling from timothyjamesbecker/sve
6c953ac5d795: Pull complete 
3eed5ff20a90: Pull complete 
f8419ea7c1b5: Pull complete 
51900bc9e720: Pull complete 
a3ed95caeb02: Pull complete 
10ce480b938a: Pull complete 
2ffce0d2b9ee: Pull complete 
92e07f53177c: Pull complete 
106781125863: Pull complete 
77bdde65f028: Pull complete 
086ab858dce6: Pull complete 
9956b2fe19fe: Pull complete 
8896ddd12c03: Pull complete 
aec863743f76: Pull complete 
0e35febd37ea: Pull complete 
d25062ed0141: Pull complete 
55b3373a6d89: Pull complete 
d4ad2040371c: Pull complete 
5975e2d8a309: Pull complete 
6799b4746041: Pull complete 
caaa0eb5c41b: Pull complete 
7867e2fda3da: Pull complete 
436b969a356f: Pull complete 
ffe9546c9592: Pull complete 
d851b3ca8e1c: Pull complete 
7ccaad6cf997: Pull complete 
9533c0f3bb48: Pull complete 
ac4b8efec95d: Pull complete 
26dec8409c56: Pull complete 
ecdc71b1cf90: Pull complete 
35fa7ad20883: Pull complete 
5af342999d4b: Pull complete 
5ecdef155038: Pull complete 
e85a7ea218e2: Pull complete 
e27f3e03ef00: Pull complete 
63126d64463a: Pull complete 
9f91d197d2ee: Pull complete 
d2ec87ae1ebe: Pull complete 
9d5c6dc77371: Pull complete 
b1ff5e8c3624: Pull complete 
3aae5631871b: Pull complete 
5c84747ac2ae: Pull complete 
9b3038f3c584: Pull complete 
9eb0a6c25b41: Pull complete 
aa697dfce869: Pull complete 
7b20c469adde: Pull complete 
57f10e6cfa69: Pull complete 
e293c35f0bd3: Pull complete 
db3f8f425660: Pull complete 
f4ed7aa0929b: Pull complete 
86c591f239c9: Pull complete 
58469006c494: Pull complete 
887682c51c2a: Pull complete 
c40afe78fcd9: Pull complete 
8cade8693741: Pull complete 
f8bdc99174d1: Pull complete 
1dcdf24c1472: Pull complete 
3e1a70853a42: Pull complete 
4b8ef892b878: Pull complete 
79865137cfa5: Pull complete 
9a6814f10a4a: Pull complete 
Digest: sha256:819269e854bb44611b221965b05c0db2b63f4dd039da2ce2db7672f3ab0b0333
Status: Downloaded newer image for timothyjamesbecker/sve:latest
start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'
dbc:['db=sve', 'pwd=sv_calibrator', 'srv=127.0.0.1', 'uid=sv_calibrator']
invalid database configuration
running the SVE without the SVEDB
processing with : ['breakdancer', 'cnvnator', 'delly', 'gatk_haplo', 'lumpy', 'pindel']
read_depth not given
read_length not given
no targets
chr selection not used scanning reference
Traceback (most recent call last):
  File "/software/SVE/scripts/variant_processor.py", line 168, in <module>
    chroms = ru.get_fasta_seq_names(ref_fa_path)
  File "/software/SVE/scripts/../read_utils.py", line 60, in get_fasta_seq_names
    for s in ht.FastaReader(fasta_path): ss+=[s.name]
  File "/usr/local/lib/python2.7/dist-packages/HTSeq/__init__.py", line 294, in __iter__
    assert seq is not None, "FASTA file does not start with '>'."
AssertionError: FASTA file does not start with '>'.
```

Can you please help me to solve the issue?

Thank you,
Tushar

**Comment by tushardave26** [comment]
Hello @timothyjamesbecker 

Can you please comment on the reported issue?

Thank you.

**Comment by timothyjamesbecker** [comment]
It looks that the FASTA file you are trying to use is malformed.  This link should provide some help: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp
